# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\" \n\x0bRoomRequest\x12\x11\n\troom_name\x18\x01 \x01(\t\"0\n\x0cRoomResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\x19\n\x08RoomList\x12\r\n\x05rooms\x18\x01 \x03(\t\"7\n\x0fUserRoomRequest\x12\x11\n\troom_name\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\"G\n\x0eMessageRequest\x12\x11\n\troom_name\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"3\n\x0fMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x0bMessageList\x12\x10\n\x08messages\x18\x01 \x03(\t2\xcc\x02\n\x0b\x43hatService\x12\x33\n\nCreateRoom\x12\x11.chat.RoomRequest\x1a\x12.chat.RoomResponse\x12(\n\tListRooms\x12\x0b.chat.Empty\x1a\x0e.chat.RoomList\x12\x35\n\x08JoinRoom\x12\x15.chat.UserRoomRequest\x1a\x12.chat.RoomResponse\x12\x36\n\tLeaveRoom\x12\x15.chat.UserRoomRequest\x1a\x12.chat.RoomResponse\x12:\n\x0bSendMessage\x12\x14.chat.MessageRequest\x1a\x15.chat.MessageResponse\x12\x33\n\x0bGetMessages\x12\x11.chat.RoomRequest\x1a\x11.chat.MessageListB\x17\x42\x15\x43hatServiceOuterClassb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\025ChatServiceOuterClass'
  _globals['_ROOMREQUEST']._serialized_start=20
  _globals['_ROOMREQUEST']._serialized_end=52
  _globals['_ROOMRESPONSE']._serialized_start=54
  _globals['_ROOMRESPONSE']._serialized_end=102
  _globals['_EMPTY']._serialized_start=104
  _globals['_EMPTY']._serialized_end=111
  _globals['_ROOMLIST']._serialized_start=113
  _globals['_ROOMLIST']._serialized_end=138
  _globals['_USERROOMREQUEST']._serialized_start=140
  _globals['_USERROOMREQUEST']._serialized_end=195
  _globals['_MESSAGEREQUEST']._serialized_start=197
  _globals['_MESSAGEREQUEST']._serialized_end=268
  _globals['_MESSAGERESPONSE']._serialized_start=270
  _globals['_MESSAGERESPONSE']._serialized_end=321
  _globals['_MESSAGELIST']._serialized_start=323
  _globals['_MESSAGELIST']._serialized_end=354
  _globals['_CHATSERVICE']._serialized_start=357
  _globals['_CHATSERVICE']._serialized_end=689
# @@protoc_insertion_point(module_scope)
